name: Playwright CI Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  full-flow:
    name: Run Full Flow Test
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name : Install Allure
        run : npm install -g allure-playwright 
      
      - name : Install allure commandline
        run : npm install allure-commandline --save-dev

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Full Flow Test with Allure
        run: npx playwright test ikea-full-flow.spec.ts --project chromium --reporter=line,allure-playwright

      - name: Generate Allure Report
        run: npx allure generate ./allure-results --clean -o ./allure-report

      - name: Upload Full Flow Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: ikea-full-flow-allure-report
          path: ./allure-report
          retention-days: 30

  smoke-tests:
    name: Run Smoke Tests
    runs-on: ubuntu-latest
    needs: full-flow

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name : Install Allure
        run : npm install -g allure-playwright 
      
      - name : Install allure commandline
        run : npm install allure-commandline --save-dev

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Smoke Tests with Allure
        run: npx playwright test --grep @smoke --project chromium --reporter=line,allure-playwright

      - name: Generate Allure Report
        run: npx allure generate ./allure-results --clean -o ./allure-report

      - name: Upload Smoke Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: smoke-allure-report
          path: ./allure-report
          retention-days: 30

  sanity-tests:
    name: Run Sanity Tests
    runs-on: ubuntu-latest
    needs: smoke-tests

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name : Install Allure
        run : npm install -g allure-playwright 
      
      - name : Install allure commandline
        run : npm install allure-commandline --save-dev
        

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Sanity Tests with Allure
        run: npx playwright test --grep @sanity --project chromium --reporter=line,allure-playwright 

      - name: Generate Allure Report
        run: npx allure generate ./allure-results --clean -o ./allure-report

      - name: Upload Sanity Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: sanity-allure-report
          path: ./allure-report
          retention-days: 30
